CREATE TABLE guestbook
(
    ID INT (32) NOT NULL AUTO_INCREMENT,
    name VARCHAR (128) NOT NULL,
    password VARCHAR (256) NOT NULL,
    email VARCHAR (256) NOT NULL,
    url VARCHAR (256) NOT NULL,
    comments TEXT NOT NULL,
    updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE (name)
);